name: Job Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_name: ${{steps.set-output.outputs.name}}

    steps:
      - name: set output
        id: set-output
        shell: bash
        run: |
          echo "name=InterviewPro" >> $GITHUB_OUTPUT
          echo "age=23" >> $GITHUB_OUTPUT
          echo "country=USA" >> $GITHUB_OUTPUT

      - name: access output
        run: |
          echo ${{ steps.set-output.outputs.name }}

  job2:
   runs-on: ubuntu-latest      
   
   steps:
      - name: access output
        run: echo ${{ steps.set-output.outputs.name }}
        
