name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'Age'
        type: number
        required: true

      gender:
        description: 'Gender'
        type: choice
        options:
          - Male
          - Female

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo ${{ inputs.name }}

      - name: Age
        run: echo ${{ inputs.age }}

      - name: Gender
        run: echo ${{ input.gender }}
        
      - name: List Environment variables
        run: env
      - name: Adding a path
        run: echo "$HOME/.m2" >> "$GITHUB_PATH"

      - name: DisplayingList Environment variables after adding '$HOME/.m2'
        run: env
