name: Set Environment Variables

on:
  push:
    branches: [ main ]

env:
  CHANNEL_NAME: InterviewPro

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
      - name: Greetings 
        run: |
          echo "Hello, ${{ env.CHANNEL_NAME }}"
          echo "Hello, $CHANNEL_NAME "

      - name: Set env variables programmatically
        run: echo "COUNT=10000" >> $GITHUB_ENV

      - name: Access env variable
        run: echo ${{ env.COUNT }}

      - name: Update env variables
        run: |
          echo "CHANNEL_NAME=Test" >> $GITHUB_ENV
          echo "COUNT=20000" >> $GITHUB_ENV

      - name: Access updated env variable
        run: |
          echo ${{ env.CHANNEL_NAME }} 
          echo ${{ env.COUNT }} 

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: |
          echo "Hello, ${{ env.CHANNEL_NAME }} from job2!"
          echo "Hello, $CHANNEL_NAME from job2!"
             
