name: Set Environment Variables

on:
  push:
    branches: [ main ]

env:
  CHANNEL_NAME: InterviewPro

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
      - name: Greetings 
        run: |
          echo "Hello, ${{ env.CHANNEL_NAME }}"
          echo "Hello, $CHANNEL_NAME "

      - name: Set env variables programmatically
        run: echo "COUNT=10000" >> $GITHUB_ENV

      - name: Access env variable
        run: echo ${{ env.COUNT }}
