name: Set Environment Variables

on:
  push:
    branches: [ main ]

env:
  CHANNEL_NAME: InterviewPro

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
      - name: Greetings 
        run: |
          echo "Hello, ${{ env.CHANNEL_NAME }}"
          echo "Hello, $CHANNEL_NAME "

      - name: Access repository variables
        run: echo ${{ vars.USERNAME }}

      - name: Access repository secret
        run: echo ${{ secrets.PASSWORD }}
