name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: set output
        id: set-output
        shell: bash
        run: echo "age=23" >> $GITHUB_OUTPUT

      - name: access output
        run: echo ${{ steps.set-output.outputs.age }}

      - name: display GITHUB_OUTPUT
        run: echo ${{ GITHUB_OUTPUT }}

        
       
