name: Built-in variables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
      - name: GitHub
        run: |
          echo "GITHUB_REF - $GITHUB_REF - ${{ github.ref }}"
          echo "GITHUB_WORKFLOW - $GITHUB_WORKFLOW - ${{ github.workflow }}"
          echo "GITHUB_RUN_ID - $GITHUB_RUN_ID - ${{ github.run_id }}"
          echo "GITHUB_REPOSITORY - $GITHUB_REPOSITORY - ${{ github.repository }}"
           
